server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
kafka:
  bootstrap-address: localhost:9092
  customer-type:
    group-id: customer-microservice-example
security:
  jwt:
    client-secret: XY7kmzoNzl100

spring:
  application:
    name: Customer Microservice
  datasource:
    url: jdbc:h2:file:~/customer-microservice-example
    username: sa
    password:
    driver-class-name: org.h2.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1
  sleuth:
    sampler:
      probability: 0.5
  zipkin:
    baseUrl: http://localhost:9411
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      expose: prometheus
      exposure:
        include: "*"